import { useCallback, useEffect, useState, type FormEvent } from "react";
import { CalendarDays, Plus, Wheat, X } from "lucide-react";
import DashboardLayout from "../../components/dashboard/DashboardLayout";
import { ErrorState, Field, LoadingState, PageHeading } from "../../components/dashboard/PageElements";
import api, { getErrorMessage } from "../../services/api";
import type { Crop, CropRecord, Farm } from "../../types/api";

const initial = { cropId: "", plantingDate: "", expectedHarvestDate: "", season: "Kharif", status: "GROWING" };
export default function Crops() {
  const [farms, setFarms] = useState<Farm[]>([]); const [farmId, setFarmId] = useState(""); const [catalog, setCatalog] = useState<Crop[]>([]); const [records, setRecords] = useState<CropRecord[]>([]); const [form, setForm] = useState(initial); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.get<Farm[]>("/farms"), api.get<Crop[]>("/crops")]).then(([farmRes, cropRes]) => { setFarms(farmRes.data); setFarmId(farmRes.data[0]?.id ?? ""); setCatalog(cropRes.data); setForm({ ...initial, cropId: cropRes.data[0]?.id ?? "" }); if (!farmRes.data.length) setLoading(false); }).catch(e => { setError(getErrorMessage(e)); setLoading(false); }); }, []);
  const loadRecords = useCallback(async () => { if (!farmId) return; setLoading(true); try { setRecords((await api.get<CropRecord[]>(`/crops/farms/${farmId}`)).data); } catch (e) { setError(getErrorMessage(e)); } finally { setLoading(false); } }, [farmId]);
  useEffect(() => { void loadRecords(); }, [loadRecords]);
  const update = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm({ ...form, [key]: event.target.value });
  async function add(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await api.post(`/crops/farms/${farmId}`, { ...form, expectedHarvestDate: form.expectedHarvestDate || null }); setOpen(false); setForm({ ...initial, cropId: catalog[0]?.id ?? "" }); await loadRecords(); } catch (e) { setError(getErrorMessage(e, "Could not add the crop record.")); } finally { setSaving(false); } }
  return <DashboardLayout><PageHeading eyebrow="CROP MANAGEMENT" title="Current crop" description="Track the crop growing on each farm and its season status." action={<div className="heading-actions">{farms.length > 0 && <select className="page-select" value={farmId} onChange={(e) => setFarmId(e.target.value)}>{farms.map(f => <option key={f.id} value={f.id}>{f.farmName}</option>)}</select>}<button className="primary-button inline-button" disabled={!farms.length} onClick={() => setOpen(true)}><Plus size={17} /> Add crop</button></div>} />{error && <div className="inline-alert">{error}</div>}{loading ? <LoadingState /> : !farms.length ? <ErrorState message="Create a farm before adding a crop." /> : records.length === 0 ? <div className="empty-workspace"><div><Wheat size={30} /></div><h2>No crop recorded yet</h2><p>Add the current crop and sowing date to improve your farm overview.</p><button className="primary-button inline-button" onClick={() => setOpen(true)}><Plus size={17} /> Add current crop</button></div> : <div className="crop-list">{records.map(record => <article className="crop-row" key={record.id}><div className="crop-icon"><Wheat size={22} /></div><div><span>{record.season || "CURRENT SEASON"}</span><h2>{record.cropName}</h2><p><CalendarDays size={14} /> Sown {new Date(record.plantingDate).toLocaleDateString()}</p></div><div className="status-pill">{record.status || "ACTIVE"}</div></article>)}</div>}
    {open && <div className="modal-backdrop"><section className="form-modal" role="dialog" aria-modal="true"><div className="modal-heading"><div><p className="eyebrow">CROP RECORD</p><h2>Add current crop</h2></div><button onClick={() => setOpen(false)} aria-label="Close"><X size={20} /></button></div><form className="record-form" onSubmit={add}><Field label="Crop"><select required value={form.cropId} onChange={update("cropId")}>{catalog.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Season"><select value={form.season} onChange={update("season")}><option>Kharif</option><option>Rabi</option><option>Zaid</option><option>Year-round</option></select></Field><Field label="Sowing date"><input required type="date" value={form.plantingDate} onChange={update("plantingDate")} /></Field><Field label="Expected harvest"><input type="date" value={form.expectedHarvestDate} onChange={update("expectedHarvestDate")} /></Field><Field label="Status"><select value={form.status} onChange={update("status")}><option>PLANNED</option><option>GROWING</option><option>READY_TO_HARVEST</option><option>HARVESTED</option></select></Field><div className="form-actions"><button type="button" className="secondary-button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button inline-button" disabled={saving}>{saving ? "Saving…" : "Save crop"}</button></div></form></section></div>}
  </DashboardLayout>;
}
