import { useEffect, useState, type FormEvent } from "react";
import { MapPin, Save, UserRound } from "lucide-react";
import DashboardLayout from "../../components/dashboard/DashboardLayout";
import { Field, LoadingState, PageHeading } from "../../components/dashboard/PageElements";
import { useAuth } from "../../hooks/AuthContext";
import api, { getErrorMessage } from "../../services/api";
import type { FarmerProfile, User } from "../../types/api";

const emptyProfile = { village: "", district: "", state: "", pincode: "", farmingType: "MIXED", irrigationType: "DRIP", totalLandAcres: "", farmingExperienceYears: "" };
export default function Profile() {
  const { user, setUser } = useAuth(); const [account, setAccount] = useState({ fullName: user?.fullName ?? "", phone: user?.phone ?? "" }); const [profile, setProfile] = useState(emptyProfile); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => { Promise.all([api.get<User>("/users/me"), api.get<FarmerProfile>("/farmer/profile").catch(() => null)]).then(([userRes, profileRes]) => { setAccount({ fullName: userRes.data.fullName, phone: userRes.data.phone ?? "" }); if (profileRes) { const p = profileRes.data; setProfile({ village:p.village??"",district:p.district??"",state:p.state??"",pincode:p.pincode??"",farmingType:p.farmingType??"MIXED",irrigationType:p.irrigationType??"DRIP",totalLandAcres:p.totalLandAcres == null ? "" : String(p.totalLandAcres),farmingExperienceYears:p.farmingExperienceYears == null ? "" : String(p.farmingExperienceYears) }); } }).catch(e => setError(getErrorMessage(e))).finally(() => setLoading(false)); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { const [userRes] = await Promise.all([api.put<User>("/users/me", account), api.put("/farmer/profile", { ...profile, totalLandAcres: profile.totalLandAcres === "" ? null : Number(profile.totalLandAcres), farmingExperienceYears: profile.farmingExperienceYears === "" ? null : Number(profile.farmingExperienceYears) })]); setUser(userRes.data); setSuccess("Profile updated successfully."); } catch (e) { setError(getErrorMessage(e, "Could not update your profile.")); } finally { setSaving(false); } }
  return <DashboardLayout><PageHeading eyebrow="FARMER PROFILE" title="Your profile" description="Keep your contact and farming details current." />{error && <div className="inline-alert">{error}</div>}{success && <div className="inline-success">{success}</div>}{loading ? <LoadingState /> : <section className="profile-layout"><aside className="profile-card"><div className="profile-avatar"><UserRound size={38} /></div><h2>{account.fullName}</h2><p>{user?.email}</p><span>FARMER ACCOUNT</span><div className="profile-location"><MapPin size={16} /> {[profile.village, profile.district, profile.state].filter(Boolean).join(", ") || "Location not added"}</div></aside><form className="record-form panel-form profile-form" onSubmit={save}><div className="form-section-title"><h2>Account information</h2><p>Used for your dashboard and contact details.</p></div><Field label="Full name"><input required minLength={2} value={account.fullName} onChange={e => setAccount({...account,fullName:e.target.value})} /></Field><Field label="Phone number"><input value={account.phone} onChange={e => setAccount({...account,phone:e.target.value})} /></Field><div className="form-section-title full-form-width"><h2>Farming profile</h2><p>Helps describe your location and farming setup.</p></div>{(["village","district","state","pincode"] as const).map(key => <Field key={key} label={key.charAt(0).toUpperCase()+key.slice(1)}><input value={profile[key]} onChange={e => setProfile({...profile,[key]:e.target.value})} /></Field>)}<Field label="Farming type"><select value={profile.farmingType} onChange={e => setProfile({...profile,farmingType:e.target.value})}><option>ORGANIC</option><option>CONVENTIONAL</option><option>MIXED</option></select></Field><Field label="Primary irrigation"><select value={profile.irrigationType} onChange={e => setProfile({...profile,irrigationType:e.target.value})}><option>DRIP</option><option>RAINFED</option><option>SPRINKLER</option><option>CANAL</option><option>TUBE_WELL</option><option>MIXED</option></select></Field><Field label="Total land (acres)"><input min="0" step="0.1" type="number" value={profile.totalLandAcres} onChange={e => setProfile({...profile,totalLandAcres:e.target.value})} /></Field><Field label="Experience (years)"><input min="0" type="number" value={profile.farmingExperienceYears} onChange={e => setProfile({...profile,farmingExperienceYears:e.target.value})} /></Field><div className="form-actions"><button className="primary-button inline-button" disabled={saving}><Save size={17} /> {saving ? "Saving…" : "Save profile"}</button></div></form></section>}</DashboardLayout>;
}
