import { useCallback, useEffect, useMemo, useState } from "react";
import { CloudSun, Droplets, FlaskConical, Info, ShieldAlert, Sparkles, Wheat } from "lucide-react";
import DashboardLayout from "../../components/dashboard/DashboardLayout";
import { ErrorState, LoadingState, PageHeading } from "../../components/dashboard/PageElements";
import api, { getErrorMessage } from "../../services/api";
import type { Farm, Recommendation, RecommendationResponse } from "../../types/api";

const icons = { IRRIGATION: Droplets, SOIL: FlaskConical, WEATHER: CloudSun, CROP: Wheat, GENERAL: Info };
type AdvisoryFilter = "ALL" | Recommendation["category"];
const filters: AdvisoryFilter[] = ["ALL", "IRRIGATION", "SOIL", "WEATHER", "CROP"];
export default function Recommendations() {
  const [farms, setFarms] = useState<Farm[]>([]); const [farmId, setFarmId] = useState(""); const [data, setData] = useState<RecommendationResponse | null>(null); const [filter, setFilter] = useState<AdvisoryFilter>("ALL"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { api.get<Farm[]>("/farms").then(({ data: farmData }) => { setFarms(farmData); setFarmId(farmData[0]?.id ?? ""); if (!farmData.length) setLoading(false); }).catch(e => { setError(getErrorMessage(e)); setLoading(false); }); }, []);
  const load = useCallback(async () => { if (!farmId) return; setLoading(true); setError(""); try { setData((await api.get<RecommendationResponse>(`/farms/${farmId}/recommendations`)).data); } catch (e) { setError(getErrorMessage(e, "Could not generate advisories.")); } finally { setLoading(false); } }, [farmId]);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => data?.recommendations.filter(item => filter === "ALL" || item.category === filter) ?? [], [data, filter]);
  return <DashboardLayout><PageHeading eyebrow="EXPLAINABLE DECISION SUPPORT" title="Smart advisories" description="Simple signals generated from your farm, crop, soil and current weather." action={farms.length ? <select className="page-select" value={farmId} onChange={e => setFarmId(e.target.value)}>{farms.map(f => <option key={f.id} value={f.id}>{f.farmName}</option>)}</select> : undefined} />{loading ? <LoadingState label="Combining farm conditions…" /> : error ? <ErrorState message={error} retry={load} /> : !farms.length ? <ErrorState message="Create a farm to receive advisories." /> : data && <><div className="advisory-notice"><ShieldAlert size={20} /><div><strong>Prototype advisory</strong><p>{data.prototypeNotice}</p></div></div><div className="filter-row" role="group" aria-label="Filter advisories by category">{filters.map(category => <button type="button" className={filter === category ? "active" : ""} aria-pressed={filter === category} onClick={() => setFilter(category)} key={category}>{category === "ALL" ? "All" : category.charAt(0) + category.slice(1).toLowerCase()}</button>)}</div>{filtered.length ? <div className="recommendation-grid">{filtered.map(item => <RecommendationCard item={item} key={item.id} />)}</div> : <div className="empty-filter"><Sparkles size={24} /><h2>No {filter === "ALL" ? "active" : filter.toLowerCase()} advisories</h2><p>Recommendations will appear when the farm signals need attention.</p></div>}<section className="explain-card"><Sparkles size={23} /><div><h2>Why the advice is explainable</h2><p>Every card shows the farm signal that triggered it. AgriSmart uses transparent prototype thresholds—not hidden machine learning or certified agronomic prescriptions.</p></div></section></>}</DashboardLayout>;
}
function RecommendationCard({ item }: { item: Recommendation }) { const Icon = icons[item.category] ?? Info; return <article className={`recommendation-card severity-${item.severity.toLowerCase()}`}><div className="recommendation-top"><div className="recommendation-icon"><Icon size={21} /></div><span>{item.severity}</span></div><p className="eyebrow">{item.category}</p><h2>{item.title}</h2><p>{item.message}</p><div className="reason-box"><strong>Why this appeared</strong><span>{item.reason}</span></div></article>; }
