import { useEffect, useState, type FormEvent } from "react";
import { FlaskConical, Save } from "lucide-react";
import DashboardLayout from "../../components/dashboard/DashboardLayout";
import { ErrorState, Field, LoadingState, PageHeading } from "../../components/dashboard/PageElements";
import api, { getErrorMessage } from "../../services/api";
import type { Farm, Soil as SoilType } from "../../types/api";

const emptySoil = { soilType: "", ph: "", nitrogen: "", phosphorus: "", potassium: "", organicCarbon: "", electricalConductivity: "", moisturePercentage: "", notes: "" };

export default function Soil() {
  const [farms, setFarms] = useState<Farm[]>([]); const [farmId, setFarmId] = useState(""); const [form, setForm] = useState(emptySoil); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => { api.get<Farm[]>("/farms").then(({ data }) => { setFarms(data); setFarmId(data[0]?.id ?? ""); if (!data.length) setLoading(false); }).catch((e) => { setError(getErrorMessage(e)); setLoading(false); }); }, []);
  useEffect(() => { if (!farmId) return; setLoading(true); setSuccess(""); api.get<SoilType>(`/farms/${farmId}/soil`).then(({ data }) => setForm(Object.fromEntries(Object.entries(emptySoil).map(([key]) => [key, data[key as keyof SoilType] == null ? "" : String(data[key as keyof SoilType])])) as typeof emptySoil)).catch(() => setForm(emptySoil)).finally(() => setLoading(false)); }, [farmId]);
  const update = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm({ ...form, [key]: event.target.value });
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { const payload = Object.fromEntries(Object.entries(form).map(([key, val]) => [key, key === "soilType" || key === "notes" ? val || null : val === "" ? null : Number(val)])); await api.put(`/farms/${farmId}/soil`, payload); setSuccess("Soil profile saved successfully."); } catch (e) { setError(getErrorMessage(e, "Could not save the soil profile.")); } finally { setSaving(false); } }
  return <DashboardLayout><PageHeading eyebrow="SOIL HEALTH" title="Soil profile" description="Keep the latest field readings together for clearer prototype advisories." action={farms.length ? <select className="page-select" value={farmId} onChange={(e) => setFarmId(e.target.value)}>{farms.map(f => <option key={f.id} value={f.id}>{f.farmName}</option>)}</select> : undefined} />{error && <div className="inline-alert">{error}</div>}{success && <div className="inline-success">{success}</div>}{loading ? <LoadingState /> : !farms.length ? <ErrorState message="Create a farm before adding a soil profile." /> : <section className="split-workspace"><aside className="soil-guide"><div><FlaskConical size={28} /></div><p className="eyebrow">FIELD SAMPLE</p><h2>Make every reading useful.</h2><p>Enter values from your latest soil test or field observation. Unknown values can be left blank.</p><ul><li>pH range accepted: 0–14</li><li>Moisture range accepted: 0–100%</li><li>Nutrients should be non-negative</li></ul></aside><form className="record-form panel-form" onSubmit={save}><Field label="Soil type"><input value={form.soilType} onChange={update("soilType")} placeholder="Black soil" /></Field><Field label="pH"><input min="0" max="14" step="0.1" type="number" value={form.ph} onChange={update("ph")} /></Field><Field label="Nitrogen"><input min="0" step="0.1" type="number" value={form.nitrogen} onChange={update("nitrogen")} /></Field><Field label="Phosphorus"><input min="0" step="0.1" type="number" value={form.phosphorus} onChange={update("phosphorus")} /></Field><Field label="Potassium"><input min="0" step="0.1" type="number" value={form.potassium} onChange={update("potassium")} /></Field><Field label="Organic carbon"><input min="0" step="0.01" type="number" value={form.organicCarbon} onChange={update("organicCarbon")} /></Field><Field label="Electrical conductivity"><input min="0" step="0.01" type="number" value={form.electricalConductivity} onChange={update("electricalConductivity")} /></Field><Field label="Moisture percentage"><input min="0" max="100" step="0.1" type="number" value={form.moisturePercentage} onChange={update("moisturePercentage")} /></Field><Field label="Field notes"><textarea value={form.notes} onChange={update("notes")} placeholder="Optional observation…" /></Field><div className="form-actions"><button className="primary-button inline-button" disabled={saving}><Save size={17} /> {saving ? "Saving…" : "Save soil profile"}</button></div></form></section>}</DashboardLayout>;
}
